### ISSUE TITLE
💭  Renaming Jtree?

### ISSUE THREAD

**Issue by breck7** [publicdomaincompany/jtree#126]
Looking to greatly improve the UX of JTree, including revisiting the name of the repo.

Because tools for building alternative 2-d and 3-d langs perhaps will be included in this
new repo, in addition to the tree notation tools, we could pick something more open ended.

Total spitball:

Absedy
AlphaBit
AlphaCube
AlphaPress
Berg
Blocks
Bricks
Brickster
Cube
CubeLang
Grid
Langster
LangPress
Notation
Notate
Notater
Symbolia
YourLang
VoxLang
Voxabit
VoxBit

**Comment by boticello** [comment]
conlang, conlingo
glossolalia, lalia
spitball, spit, breeze
burble, mutter
cant, patois

**Comment by breck7** [comment]
Oh I like these @boticello. Spitball, Breeze and Burble especially. Thanks!

**Comment by boticello** [comment]
What about tree-related words? Like acorn, sapling, shrub, or bark...

**Comment by breck7** [comment]
The question I'm mining on is whether to use a term that is more general than a tree shape. While all structures are trees, trees evoke a certain shape, and there are increasingly 2D and 3D symbolic languages that don't quite evoke that shape. Although, they are always connected by some invisible spine. Sorry this is very abstract. Not an urgent priority, perhaps something to do in the next 6 months to 6 years.

**Comment by breck7** [comment]
Going to punt on this for probably a year or so
